version: "3"
services:
  plex:
    image: greensheep/plex-server-docker-rpi:1.29.1.6316-f4cdfea9c
    container_name: plex
    network_mode: "host"
#    ports:
#      - "${PLEX_PORT:-32400}:32400"
    restart: always
    volumes:
      - ${CONFIG_VOLUME}:/config
      - ${MEDIA_VOLUME}:/data
