version: "3"
services:
  n8n:
    image: n8nio/n8n:0.84.1-rpi
    container_name: n8n
    environment:
      TZ: ${TZ}
    ports:
        - ${PORT}:5678
    volumes: 
        - ${DATA_VOLUME}:/home/node/.n8n
    restart: always
