version: "3.5"

services:
  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: dyndns
    environment:
      - "TZ=America/Los_Angeles"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TYPE=A"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TTL=300"
      - "DDNSR53_CREDENTIALS_ACCESSKEYID=${AWS_ACCESS_KEY}"
      - "DDNSR53_CREDENTIALS_SECRETACCESSKEY=${AWS_SECRET_KEY}"
      - "DDNSR53_ROUTE53_HOSTEDZONEID=${AWS_ZONEID}"
      - "DDNSR53_ROUTE53_RECORDSSET_0_NAME=${AWS_RECORDSET}."
    restart: always
